services:
  db:
    image: postgres:16-alpine
    container_name: ledture-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ledture
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    name: ledture-db-storage
