name: Frontend Deployment

on:
    push:
        tags:
            - 'v*'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            BASE_API_URL: ${{ vars.BASE_API_URL }}

        steps:
        -   name: Checkout
            uses: actions/checkout@v6

        -   name: Setup Node
            uses: actions/setup-node@v6
            with:
                node-version: 24

        -   name: Install dependencies
            working-directory: frontend
            run: npm ci

        -   name: Create .env file
            working-directory: frontend
            run: echo "VITE_BASE_API_URL=$BASE_API_URL" > .env && ls -la && echo $PWD

        -   working-directory: fontend
            run: cat .env

        -   name: Build
            working-directory: frontend
            run: npm run build

        -   name: Setup Pages
            uses: actions/configure-pages@v5

        -   name: Upload artifact
            uses: actions/upload-pages-artifact@v4
            with:
                path: frontend/dist

        -   name: Deploy
            uses: actions/deploy-pages@v4